### ISSUE TITLE
Confusing explanation on time course experiment

### ISSUE THREAD

**Issue by kehey** [mikelove/rnaseqGene#1]
> The following chunk of code performs a likelihood ratio test, where we remove
the strain-specific differences over time. Genes with small *p* values
from this test are those which at one or more time points after time
0 showed a strain-specific effect. Note therefore that this will not
give small *p* values to genes that moved up or down over time in the
same way in both strains.

On the first sentence, should this not be "where we remove
the **non** strain-specific differences over time? Or otherwise put, the differences over time that are independent of the strain.

Because you go on to say that genes that react in the same way in both strains are do not receive a small p-value.

**Comment by mikelove** [comment]
It’s correct as written and the reason is how the LRT works. Take a look at the DESeq2 vignette.
