### ISSUE TITLE
Wrong link and workflow not available for Bioc 3.18

### ISSUE THREAD

**Issue by ATpoint** [mikelove/rnaseqGene#5]
Hi Mike, please check the link at https://github.com/thelovelab/rnaseqGene/commit/712f039d929a1affa97d047322fd11728c7b7e8a -- thelove**lab**, not thelove**love** ;-)

Not sure if this has any consequence causing this: https://support.bioconductor.org/p/9155029/ or whether it simply has not been built for 3.18 yet?

**Comment by mikelove** [comment]
thanks fixed!

I don't think that's the cause. i'll take a look
